CREATE TABLE "app_settings" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"key" text NOT NULL,
	"value" text NOT NULL,
	"description" text,
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "app_settings_key_unique" UNIQUE("key")
);
--> statement-breakpoint
CREATE TABLE "bills" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"bill_number" text NOT NULL,
	"customer_name" text NOT NULL,
	"customer_email" text NOT NULL,
	"customer_phone" text NOT NULL,
	"customer_address" text NOT NULL,
	"currency" text DEFAULT 'INR',
	"subtotal" numeric(12, 2) NOT NULL,
	"making_charges" numeric(12, 2) NOT NULL,
	"gst" numeric(12, 2) NOT NULL,
	"vat" numeric(12, 2) DEFAULT '0' NOT NULL,
	"discount" numeric(12, 2) DEFAULT '0' NOT NULL,
	"total" numeric(12, 2) NOT NULL,
	"paid_amount" numeric(12, 2) NOT NULL,
	"payment_method" text DEFAULT 'CASH',
	"items" jsonb NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "bills_bill_number_unique" UNIQUE("bill_number")
);
--> statement-breakpoint
CREATE TABLE "cart_items" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"session_id" text NOT NULL,
	"user_id" varchar,
	"product_id" varchar NOT NULL,
	"quantity" integer DEFAULT 1 NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "categories" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"description" text,
	"parent_id" varchar,
	"display_order" integer DEFAULT 0,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "categories_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "delivery_attempts" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"shipment_id" varchar NOT NULL,
	"attempt_number" integer NOT NULL,
	"attempt_date" timestamp NOT NULL,
	"status" text NOT NULL,
	"reason" text,
	"notes" text,
	"next_attempt_date" timestamp,
	"delivered_to" text,
	"signature" text,
	"photo_proof" text,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "estimates" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"quotation_no" text NOT NULL,
	"customer_name" text NOT NULL,
	"customer_phone" text NOT NULL,
	"customer_email" text,
	"product_name" text NOT NULL,
	"category" text NOT NULL,
	"purity" text NOT NULL,
	"gross_weight" numeric(8, 2) NOT NULL,
	"net_weight" numeric(8, 2) NOT NULL,
	"product_code" text NOT NULL,
	"metal_value" numeric(10, 2) NOT NULL,
	"making_charges_percentage" numeric(5, 2) NOT NULL,
	"making_charges" numeric(10, 2) NOT NULL,
	"stone_diamond_charges_percentage" numeric(5, 2) DEFAULT '0',
	"stone_diamond_charges" numeric(10, 2) DEFAULT '0',
	"wastage_percentage" numeric(5, 2) DEFAULT '2',
	"wastage_charges" numeric(10, 2) NOT NULL,
	"hallmarking_charges" numeric(10, 2) DEFAULT '450',
	"subtotal" numeric(10, 2) NOT NULL,
	"total_amount" numeric(10, 2) NOT NULL,
	"currency" text DEFAULT 'INR' NOT NULL,
	"valid_until" timestamp NOT NULL,
	"status" text DEFAULT 'PENDING' NOT NULL,
	"sent_to_whatsapp" boolean DEFAULT false,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "home_section_items" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"section_id" varchar NOT NULL,
	"product_id" varchar NOT NULL,
	"display_name" text,
	"display_price" text,
	"display_price_inr" text,
	"display_price_bhd" text,
	"custom_image_url" text,
	"position" integer DEFAULT 0 NOT NULL,
	"size" text DEFAULT 'normal',
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "home_sections" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" text NOT NULL,
	"subtitle" text,
	"description" text,
	"layout_type" text DEFAULT 'grid' NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"display_order" integer DEFAULT 0,
	"background_color" text DEFAULT '#fff8e1',
	"text_color" text DEFAULT '#8b4513',
	"festival_image" text,
	"show_countdown" boolean DEFAULT false NOT NULL,
	"countdown_start_date" timestamp,
	"countdown_end_date" timestamp,
	"countdown_title" text,
	"countdown_description" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "metal_rates" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"metal" text NOT NULL,
	"purity" text NOT NULL,
	"price_per_gram_inr" numeric(10, 2) NOT NULL,
	"price_per_gram_bhd" numeric(10, 3) NOT NULL,
	"price_per_gram_usd" numeric(10, 2) NOT NULL,
	"market" text NOT NULL,
	"source" text NOT NULL,
	"last_updated" timestamp DEFAULT now(),
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "notification_campaigns" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"type" text NOT NULL,
	"target_audience" text DEFAULT 'all' NOT NULL,
	"target_segment" jsonb,
	"template_id" varchar NOT NULL,
	"channels" jsonb NOT NULL,
	"scheduled_at" timestamp,
	"launched_at" timestamp,
	"completed_at" timestamp,
	"status" text DEFAULT 'draft' NOT NULL,
	"total_recipients" integer DEFAULT 0,
	"emails_sent" integer DEFAULT 0,
	"sms_sent" integer DEFAULT 0,
	"whatsapp_sent" integer DEFAULT 0,
	"total_delivered" integer DEFAULT 0,
	"total_failed" integer DEFAULT 0,
	"budget_limit" numeric(10, 2),
	"current_spend" numeric(10, 2) DEFAULT '0',
	"created_by" varchar NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "notification_preferences" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"order_updates_email" boolean DEFAULT true,
	"order_updates_sms" boolean DEFAULT true,
	"order_updates_whatsapp" boolean DEFAULT false,
	"promotional_email" boolean DEFAULT true,
	"promotional_sms" boolean DEFAULT false,
	"promotional_whatsapp" boolean DEFAULT false,
	"product_launch_email" boolean DEFAULT true,
	"product_launch_sms" boolean DEFAULT false,
	"product_launch_whatsapp" boolean DEFAULT false,
	"personalized_email" boolean DEFAULT true,
	"personalized_sms" boolean DEFAULT false,
	"personalized_whatsapp" boolean DEFAULT false,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "notification_templates" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"type" text NOT NULL,
	"channels" jsonb DEFAULT '["email"]'::jsonb NOT NULL,
	"email_subject" text,
	"email_html_template" text,
	"email_text_template" text,
	"sms_template" text,
	"whatsapp_template" text,
	"whatsapp_media_url" text,
	"variables" jsonb DEFAULT '[]'::jsonb,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "notification_templates_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "notifications" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar,
	"session_id" text,
	"template_id" varchar,
	"type" text NOT NULL,
	"channel" text NOT NULL,
	"recipient_email" text,
	"recipient_phone" text,
	"recipient_name" text,
	"subject" text,
	"html_content" text,
	"text_content" text,
	"media_url" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"sent_at" timestamp,
	"delivered_at" timestamp,
	"failed_at" timestamp,
	"error_message" text,
	"external_id" text,
	"external_status" text,
	"order_id" uuid,
	"product_id" varchar,
	"campaign_id" varchar,
	"template_variables" jsonb DEFAULT '{}'::jsonb,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "orders" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"order_number" text NOT NULL,
	"customer_name" text NOT NULL,
	"customer_email" text NOT NULL,
	"customer_phone" text NOT NULL,
	"customer_address" text NOT NULL,
	"currency" text DEFAULT 'INR',
	"subtotal" numeric(12, 2) NOT NULL,
	"making_charges" numeric(12, 2) NOT NULL,
	"gst" numeric(12, 2) NOT NULL,
	"vat" numeric(12, 2) DEFAULT '0' NOT NULL,
	"discount" numeric(12, 2) DEFAULT '0' NOT NULL,
	"shipping" numeric(12, 2) DEFAULT '0' NOT NULL,
	"total" numeric(12, 2) NOT NULL,
	"paid_amount" numeric(12, 2) NOT NULL,
	"payment_method" text DEFAULT 'CASH',
	"payment_status" text DEFAULT 'PENDING' NOT NULL,
	"order_status" text DEFAULT 'PENDING' NOT NULL,
	"stripe_payment_intent_id" text,
	"items" jsonb NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "orders_order_number_unique" UNIQUE("order_number")
);
--> statement-breakpoint
CREATE TABLE "products" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"description" text NOT NULL,
	"category" text NOT NULL,
	"sub_category" text,
	"material" text DEFAULT 'GOLD_22K',
	"price_inr" numeric(10, 2) NOT NULL,
	"price_bhd" numeric(10, 3) NOT NULL,
	"gross_weight" numeric(8, 2) NOT NULL,
	"net_weight" numeric(8, 2) NOT NULL,
	"purity" text,
	"gemstones" jsonb DEFAULT '[]'::jsonb,
	"size" text,
	"gender" text DEFAULT 'UNISEX',
	"occasion" text,
	"stock" integer DEFAULT 0 NOT NULL,
	"images" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"is_featured" boolean DEFAULT false NOT NULL,
	"is_new_arrival" boolean DEFAULT false NOT NULL,
	"metal_type" text DEFAULT 'GOLD',
	"is_metal_price_based" boolean DEFAULT false NOT NULL,
	"making_charges_percentage" numeric(5, 2) DEFAULT '15.00',
	"custom_price_inr" numeric(10, 2),
	"custom_price_bhd" numeric(10, 3),
	"product_code" text,
	"stones" text DEFAULT 'None',
	"gold_rate_at_creation" numeric(10, 2),
	"barcode" text,
	"barcode_image_url" text,
	"created_at" timestamp DEFAULT now(),
	CONSTRAINT "products_product_code_unique" UNIQUE("product_code")
);
--> statement-breakpoint
CREATE TABLE "promotional_banners" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" text NOT NULL,
	"subtitle" text,
	"description" text,
	"banner_type" text DEFAULT 'discount' NOT NULL,
	"discount_percent" integer,
	"discount_amount" numeric(10, 2),
	"currency" text DEFAULT 'INR',
	"promo_code" text,
	"has_countdown" boolean DEFAULT false NOT NULL,
	"countdown_start_date" timestamp,
	"countdown_end_date" timestamp,
	"countdown_title" text,
	"countdown_text" text,
	"banner_image" text,
	"mobile_image" text,
	"background_image" text,
	"background_color" text DEFAULT '#f59e0b',
	"text_color" text DEFAULT '#ffffff',
	"accent_color" text DEFAULT '#dc2626',
	"layout_type" text DEFAULT 'hero' NOT NULL,
	"position" text DEFAULT 'top',
	"display_order" integer DEFAULT 0,
	"is_full_width" boolean DEFAULT true NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"is_sticky" boolean DEFAULT false NOT NULL,
	"show_on_mobile" boolean DEFAULT true NOT NULL,
	"show_on_desktop" boolean DEFAULT true NOT NULL,
	"target_pages" text[] DEFAULT ARRAY['home']::text[],
	"min_order_value" numeric(10, 2),
	"max_usage" integer,
	"current_usage" integer DEFAULT 0,
	"cta_text" text DEFAULT 'Shop Now',
	"cta_link" text DEFAULT '/collections',
	"cta_color" text DEFAULT '#ffffff',
	"cta_background_color" text DEFAULT '#dc2626',
	"valid_from" timestamp,
	"valid_until" timestamp,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "shipments" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"order_id" uuid NOT NULL,
	"tracking_number" text,
	"carrier" text NOT NULL,
	"shipping_method_id" varchar NOT NULL,
	"sender_name" text DEFAULT 'Palaniappa Jewellers' NOT NULL,
	"sender_address" text NOT NULL,
	"sender_city" text NOT NULL,
	"sender_state" text NOT NULL,
	"sender_country" text NOT NULL,
	"sender_postal_code" text NOT NULL,
	"sender_phone" text NOT NULL,
	"recipient_name" text NOT NULL,
	"recipient_address" text NOT NULL,
	"recipient_city" text NOT NULL,
	"recipient_state" text NOT NULL,
	"recipient_country" text NOT NULL,
	"recipient_postal_code" text NOT NULL,
	"recipient_phone" text NOT NULL,
	"recipient_email" text,
	"package_weight" numeric(8, 3) NOT NULL,
	"package_dimensions" jsonb,
	"package_value" numeric(10, 2) NOT NULL,
	"package_currency" text DEFAULT 'INR',
	"items_description" text NOT NULL,
	"is_fragile" boolean DEFAULT true,
	"requires_signature" boolean DEFAULT true,
	"shipping_cost" numeric(10, 2) NOT NULL,
	"insurance_cost" numeric(10, 2) DEFAULT '0',
	"total_cost" numeric(10, 2) NOT NULL,
	"status" text DEFAULT 'CREATED' NOT NULL,
	"estimated_delivery_date" timestamp,
	"actual_delivery_date" timestamp,
	"tracking_events" jsonb DEFAULT '[]'::jsonb,
	"last_tracking_update" timestamp,
	"notes" text,
	"special_instructions" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "shipments_tracking_number_unique" UNIQUE("tracking_number")
);
--> statement-breakpoint
CREATE TABLE "shipping_methods" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"zone_id" varchar NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"carrier" text,
	"estimated_days" integer NOT NULL,
	"max_days" integer,
	"base_cost" numeric(10, 2) NOT NULL,
	"per_kg_cost" numeric(10, 2) DEFAULT '0',
	"free_shipping_threshold" numeric(10, 2),
	"currency" text DEFAULT 'INR',
	"tracking_available" boolean DEFAULT true,
	"signature_required" boolean DEFAULT false,
	"insurance_included" boolean DEFAULT false,
	"max_weight" numeric(8, 2),
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "shipping_zones" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"countries" jsonb NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "user_activity" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar,
	"session_id" text,
	"activity_type" text NOT NULL,
	"page" text,
	"product_id" varchar,
	"category_id" varchar,
	"search_query" text,
	"video_id" varchar,
	"metadata" jsonb DEFAULT '{}'::jsonb,
	"duration" integer,
	"user_agent" text,
	"ip_address" text,
	"referrer" text,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" text NOT NULL,
	"password" text NOT NULL,
	"name" text NOT NULL,
	"phone" text,
	"role" text DEFAULT 'guest' NOT NULL,
	"stripe_customer_id" text,
	"stripe_subscription_id" text,
	"otp_code" text,
	"otp_expiry" timestamp,
	"otp_verified" boolean DEFAULT false,
	"created_at" timestamp DEFAULT now(),
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "videos" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"video_url" text NOT NULL,
	"thumbnail_url" text,
	"product_id" varchar NOT NULL,
	"duration" integer,
	"view_count" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"is_featured" boolean DEFAULT false NOT NULL,
	"display_order" integer DEFAULT 0,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
